

export const ADD_TEAM_MEMBER ='ADD_TEAM_MEMBER';
export const DELETE_TEAM_MEMBER ='DELETE_TEAM_MEMBER';


// export const PACKAGE_CREATE ='PACKAGE_CREATE';
// export const PACKAGE_EDIT ='PACKAGE_EDIT';
// export const PACKAGE_VIEW ='PACKAGE_VIEW';
// export const PACKAGE_DELETE ='PACKAGE_DELETE';

// export const QUESTION_TEMPLATE_CREATE ='QUESTION_TEMPLATE_CREATE';
// export const QUESTION_TEMPLATE_EDIT ='QUESTION_TEMPLATE_EDIT';
// export const QUESTION_TEMPLATE_VIEW ='QUESTION_TEMPLATE_VIEW';
// export const QUESTION_TEMPLATE_DELETE ='QUESTION_TEMPLATE_DELETE';

// export const ROLE_CREATE ='ROLE_CREATE';
// export const ROLE_EDIT ='ROLE_EDIT';
// export const ROLE_VIEW ='ROLE_VIEW';
// export const ROLE_DELETE ='ROLE_DELETE';


// export const ITEM_CREATE ='ITEM_CREATE';
// export const ITEM_EDIT ='ITEM_EDIT';
// export const ITEM_VIEW ='ITEM_VIEW';
// export const ITEM_DELETE ='ITEM_DELETE';


// export const UNIT_ITEM_CREATE ='UNIT_ITEM_CREATE';
// export const UNIT_ITEM_DELETE ='UNIT_ITEM_DELETE';
// export const UNIT_ITEM_EDIT ='UNIT_ITEM_EDIT';
// export const UNIT_ITEM_VIEW ='UNIT_ITEM_VIEW';


// export const ROLE_PERMISSION_ASSIGN ='ROLE_PERMISSION_ASSIGN';
// export const ROLE_PERMISSION_VIEW ='ROLE_PERMISSION_VIEW';
// export const ROLE_PERMISSION_DELETE ='ROLE_PERMISSION_DELETE';

// export const SERVICE_CATEGORY_CREATE ='SERVICE_CATEGORY_CREATE';
// export const SERVICE_CATEGORY_EDIT ='SERVICE_CATEGORY_EDIT';
// export const SERVICE_CATEGORY_VIEW ='SERVICE_CATEGORY_VIEW';
// export const SERVICE_CATEGORY_DELETE ='SERVICE_CATEGORY_DELETE';

// export const COMPANY_VIEW ='COMPANY_VIEW';
// export const COMPANY_CREATE ='COMPANY_CREATE';
// export const COMPANY_STATUS_CHANGE ='COMPANY_STATUS_CHANGE';
// export const COMPANY_DELETE ='COMPANY_DELETE';
// export const COMPANY_EDIT ='COMPANY_EDIT';

// export const SUBSCRIPTION_VIEW ='SUBSCRIPTION_VIEW';
// export const SUBSCRIPTION_APPROVE ='SUBSCRIPTION_APPROVE';
// export const SUBSCRIPTION_DELETE ='SUBSCRIPTION_DELETE';

// export const SETTING_CREATE ='SETTING_CREATE';
// export const SETTING_EDIT ='SETTING_EDIT';
// export const SETTING_VIEW ='SETTING_VIEW';
// export const SETTING_DELETE ='SETTING_DELETE';




